version: '3'

services:
    mongo:
        image: mongo:4.2.16
        volumes:
            - ./data/mongo/:/data/db/
        ports:
            - 127.0.0.1:27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=scenic-lob-walker-anima-sauld-bikini-repile

    redis:
        image: redis:6.2.5-alpine3.14
        command: redis-server --requirepass pernyi-awmous-leanly-crotin-shoop-cotula-embira
        ports:
            - 127.0.0.1:6379:6379

    service.python:
        build:
            dockerfile: dockerfile
            context: service/python/
        environment:
            - MONGO_HOST=mongo
            - MONGO_PASSWORD=scenic-lob-walker-anima-sauld-bikini-repile
            - REDIS_HOST=redis
        ports:
            - 81:80
        depends_on:
            - mongo
            - redis

    service.node:
        build:
            dockerfile: dockerfile
            context: service/node/
        environment:
            - MONGO_HOST=mongo
            - MONGO_PASSWORD=scenic-lob-walker-anima-sauld-bikini-repile
            - REDIS_HOST=redis
        # ports:
        #     - 83-100:80
        depends_on:
            - mongo
            - redis

    nginx.node:
        image: nginx:1.21.3-alpine
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 82:80
        depends_on:
            - service.node
